backend:
  name: github
  repo: 24jj1a0457-boop/team-chhaava
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
